### ISSUE TITLE
rds setup time out error

### ISSUE THREAD

**Issue by jsitu777** [awslabs/kubeflow-manifests#297]
**Describe the bug**
-may need to increase the wait time for the "wait_for_rds_db_instance_to_become_available" function in rds-s3 auto setup script.
-run into time out error several times when using he script. After the rds time out occurs, the subsequent cluster secret and pipeline setup (applying secret store csi drivers) will be suspended. 
-advise to increase the wait time limit from **900 to 1200** for now. 

**Steps To Reproduce**
-run rds s3 script as instructed: https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide/ 

**Expected behavior**
rds and s3 resources configured with cluster after running the script.

**Environment**
* Kubernetes version
1.21
* Using EKS (yes/no), if so version?
yes. 
* Kubeflow version
v 1.5.1
* AWS build number
* AWS service targeted (S3, RDS, etc.)

**Screenshots**
```
Waiting for RDS DB instance to become available...
Traceback (most recent call last):
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/rds-s3/auto-rds-s3-setup.py", line 623, in <module>
    main()
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/rds-s3/auto-rds-s3-setup.py", line 37, in main
    setup_rds(rds_client, secrets_manager_client, eks_client, ec2_client)
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/rds-s3/auto-rds-s3-setup.py", line 165, in setup_rds
    db_root_password = setup_db_instance(
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/rds-s3/auto-rds-s3-setup.py", line 189, in setup_db_instance
    return create_db_instance(
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/rds-s3/auto-rds-s3-setup.py", line 271, in create_db_instance
    wait_for_rds_db_instance_to_become_available(rds_client)
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/rds-s3/auto-rds-s3-setup.py", line 315, in wait_for_rds_db_instance_to_become_available
    wait_for(callback, 900)
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/utils.py", line 84, in wait_for
    raise e
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/utils.py", line 79, in wait_for
    return callback()
  File "/Users/jsitu/Dev/forked-kubeflow/kubeflow-manifests/tests/e2e/utils/rds-s3/auto-rds-s3-setup.py", line 311, in callback
    assert status == "available"
AssertionError
```

**Additional context**

Function in script:
```def wait_for_rds_db_instance_to_become_available(rds_client):

    print("Waiting for RDS DB instance to become available...")

    def callback():
        status = rds_client.describe_db_instances(
            DBInstanceIdentifier=DB_INSTANCE_NAME
        )["DBInstances"][0]["DBInstanceStatus"]
        if status == "failed":
            raise WaitForCircuitBreakerError(
                "An unexpected error occurred while waiting for the RDS DB instance to become available!"
            )
        assert status == "available"
        if status == "available":
            print("RDS DB instance is available!")

    wait_for(callback, 900)
```

**Comment by wenjinsitu** [comment]
@rrrkharse @surajkota

**Comment by surajkota** [comment]
+1 increase timeout for now until we have IaC

**Comment by AlexandreBrown** [comment]
I suspect that the time difference might come from different region availability (could be wrong, just a thought).  
Maybe giving the user a param to have the ability to override the default timeout would be a good compromise for now.  
What do you think @surajkota ? Just a thought anyway.

**Comment by wenjinsitu** [comment]
> I could be wrong about this but I suspect that the difference in the time it takes to spin up the RDS instance compared to my tests (for me it is very quick) might come from the different region availabilities (different regions than the one tested might have slower spawn time due to less availability or generally slower region). Maybe giving the user a param to have the ability to override the default timeout would be a good compromise for now.
> 
> This way we prevent having a case where 1200 is still too quick for a user but 1500 would have been ok etc.
> 
> What do you think @surajkota ? Just a thought anyway.

A bit more context about region. I was spinning up the rds instance in us-west-2 or ca-central-1, and I'm based in the bay area.
