### ISSUE TITLE
Not able to recover crashed training-operator pod 

### ISSUE THREAD

**Issue by kanwaljitkhurmi** [awslabs/kubeflow-manifests#298]
**Describe the bug**

Not able to run PyTorch component in KFP pipeline. It got stuck in wait condition and when it timed out , it crashed the operator. Not able to recover the operator right now. 

``` 
Admin:~/environment $ kubectl logs training-operator-795c5cb864-rprqb -n kubeflow
I0719 20:40:32.877075       1 request.go:645] Throttling request took 1.004473777s, request: GET:https://10.100.0.1:443/apis/serving.knative.dev/v1?timeout=32s
2022-07-19T20:40:33.781Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2022-07-19T20:40:33.874Z        INFO    setup   starting manager
2022-07-19T20:40:33.875Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
2022-07-19T20:40:33.875Z        INFO    controller-runtime.manager.controller.xgboostjob-controller     Starting EventSource    {"source": "kind source: /, Kind="}
2022-07-19T20:40:33.875Z        INFO    controller-runtime.manager.controller.mxjob-controller  Starting EventSource    {"source": "kind source: /, Kind="}
2022-07-19T20:40:33.875Z        INFO    controller-runtime.manager.controller.tfjob-controller  Starting EventSource    {"source": "kind source: /, Kind="}
2022-07-19T20:40:33.875Z        INFO    controller-runtime.manager.controller.pytorchjob-controller     Starting EventSource    {"source": "kind source: /, Kind="}
2022-07-19T20:40:34.376Z        INFO    controller-runtime.manager.controller.tfjob-controller  Starting EventSource    {"source": "kind source: /, Kind="}
2022-07-19T20:40:34.376Z        INFO    controller-runtime.manager.controller.pytorchjob-controller     Starting EventSource    {"source": "kind source: /, Kind="}
E0719 20:40:34.377164       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 430 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17ed1c0, 0xc000b4d1a0)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/runtime/runtime.go:48 +0x82
panic(0x17ed1c0, 0xc000b4d1a0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/kubeflow/tf-operator/pkg/apis/pytorch/v1.setDefaultPort(0xc000b06d00)
        /workspace/pkg/apis/pytorch/v1/defaults.go:46 +0x348
github.com/kubeflow/tf-operator/pkg/apis/pytorch/v1.SetDefaults_PyTorchJob(0xc0002fe600)
        /workspace/pkg/apis/pytorch/v1/defaults.go:103 +0x125
github.com/kubeflow/tf-operator/pkg/apis/pytorch/v1.SetObjectDefaults_PyTorchJob(...)
        /workspace/pkg/apis/pytorch/v1/zz_generated.defaults.go:35
github.com/kubeflow/tf-operator/pkg/apis/pytorch/v1.RegisterDefaults.func1(0x18987c0, 0xc0002fe600)
        /workspace/pkg/apis/pytorch/v1/zz_generated.defaults.go:29 +0x3c
k8s.io/apimachinery/pkg/runtime.(*Scheme).Default(0xc000398150, 0x1b4e860, 0xc0002fe600)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/runtime/scheme.go:365 +0xb5
github.com/kubeflow/tf-operator/pkg/controller.v1/pytorch.(*PyTorchJobReconciler).onOwnerCreateFunc.func1(0x1bb8b00, 0xc0002fe600, 0x1bb8b00)
        /workspace/pkg/controller.v1/pytorch/pytorchjob_controller.go:447 +0x7f
sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Create(...)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/predicate/predicate.go:71
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnAdd(0x1b89820, 0x27ed000, 0x1ba0dc0, 0xc0002fcd00, 0xc000705b10, 0x1, 0x1, 0x18987c0, 0xc0002fe600)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/source/internal/eventsource.go:57 +0xd1
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/pkg/mod/k8s.io/client-go@v0.19.9/tools/cache/shared_informer.go:777 +0x129
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000537f60)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0007e3f60, 0x1b46440, 0xc000b57800, 0x16a5301, 0xc000b74180)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000537f60, 0x3b9aca00, 0x0, 0x1, 0xc000b74180)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000b59100)
        /go/pkg/mod/k8s.io/client-go@v0.19.9/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00061d6b0, 0xc000b47f00)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:71 +0x62
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 430 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/runtime/runtime.go:55 +0x105
panic(0x17ed1c0, 0xc000b4d1a0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/kubeflow/tf-operator/pkg/apis/pytorch/v1.setDefaultPort(0xc000b06d00)
        /workspace/pkg/apis/pytorch/v1/defaults.go:46 +0x348
github.com/kubeflow/tf-operator/pkg/apis/pytorch/v1.SetDefaults_PyTorchJob(0xc0002fe600)
        /workspace/pkg/apis/pytorch/v1/defaults.go:103 +0x125
github.com/kubeflow/tf-operator/pkg/apis/pytorch/v1.SetObjectDefaults_PyTorchJob(...)
        /workspace/pkg/apis/pytorch/v1/zz_generated.defaults.go:35
github.com/kubeflow/tf-operator/pkg/apis/pytorch/v1.RegisterDefaults.func1(0x18987c0, 0xc0002fe600)
        /workspace/pkg/apis/pytorch/v1/zz_generated.defaults.go:29 +0x3c
k8s.io/apimachinery/pkg/runtime.(*Scheme).Default(0xc000398150, 0x1b4e860, 0xc0002fe600)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/runtime/scheme.go:365 +0xb5
github.com/kubeflow/tf-operator/pkg/controller.v1/pytorch.(*PyTorchJobReconciler).onOwnerCreateFunc.func1(0x1bb8b00, 0xc0002fe600, 0x1bb8b00)
        /workspace/pkg/controller.v1/pytorch/pytorchjob_controller.go:447 +0x7f
sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Create(...)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/predicate/predicate.go:71
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnAdd(0x1b89820, 0x27ed000, 0x1ba0dc0, 0xc0002fcd00, 0xc000705b10, 0x1, 0x1, 0x18987c0, 0xc0002fe600)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/source/internal/eventsource.go:57 +0xd1
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/pkg/mod/k8s.io/client-go@v0.19.9/tools/cache/shared_informer.go:777 +0x129
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000537f60)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00058ff60, 0x1b46440, 0xc000b57800, 0x16a5301, 0xc000b74180)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000537f60, 0x3b9aca00, 0x0, 0x1, 0xc000b74180)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000b59100)
        /go/pkg/mod/k8s.io/client-go@v0.19.9/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00061d6b0, 0xc000b47f00)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/pkg/mod/k8s.io/apimachinery@v0.19.9/pkg/util/wait/wait.go:71 +0x62 
```

KFP Pipeline with PyTorch Operator Component:
```
@dsl.pipeline(name="PyTorch Training pipeline", description="Sample training job test")
def pytorch_cnn_n_b_yaml(
    namespace=kanwal_namespace
):
    
    train_task = pytorch_job_op(
        name='pytorch-cnn-dist-file-c3', 
        namespace='kubeflow-user-example-com', 
        master_spec='{ \
          "replicas": 1, \
          "restartPolicy": "OnFailure", \
          "template": { \
            "metadata": { \
              "annotations": { \
                "sidecar.istio.io/inject": "false" \
              } \
            }, \
            "spec": { \
              "containers": [ \
                { \
                  "name": "pytorch1", \
                  "image": "763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.12.0-gpu-py38-cu116-ubuntu20.04-e3", \
                  "args": [ \
                    "python", \
                    "./sc-claim-dlc/mnist.py", \
                    "--epochs", "5", \
                    "--seed", "7", \
                    "--log-interval", "60" \
                  ], \
                  "resources": { \
                    "limits": { \
                      "nvidia.com/gpu": 2 \
                    } \
                  }, \
                  "volumeMounts": [ \
                    { \
                      "mountPath": "/sc-claim-dlc", \
                      "name": "sc-claim-dlc" \
                    } \
                  ] \
                } \
              ], \
              "volumes": [ \
                { \
                  "name": "sc-claim-dlc", \
                  "persistentVolumeClaim": { \
                    "claimName": "sc-claim-dlc" \
                  } \
                } \
              ] \
            } \
          } \
        }', 
        worker_spec='{ \
          "replicas": 1, \
          "restartPolicy": "OnFailure", \
          "template": { \
            "metadata": { \
              "annotations": { \
                "sidecar.istio.io/inject": "false" \
              } \
            }, \
            "spec": { \
              "containers": [ \
                { \
                  "name": "pytorch2", \
                  "image": "763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.12.0-gpu-py38-cu116-ubuntu20.04-e3", \
                  "args": [ \
                    "python", \
                    "./sc-claim-dlc/mnist.py", \
                    "--epochs", "5", \
                    "--seed", "7", \
                    "--log-interval", "60" \
                  ], \
                  "resources": { \
                    "limits": { \
                      "nvidia.com/gpu": 1 \
                    } \
                  }, \
                  "volumeMounts": [ \
                    { \
                      "mountPath": "/sc-claim-dlc", \
                      "name": "sc-claim-dlc" \
                    } \
                  ] \
                } \
              ], \
              "volumes": [ \
                { \
                  "name": "sc-claim-dlc", \
                  "persistentVolumeClaim": { \
                    "claimName": "sc-claim-dlc" \
                  } \
                } \
              ] \
            } \
          } \
        }',
        delete_after_done=False
    )
    ```

**Steps To Reproduce**

**Expected behavior**

**Environment**
* Kubernetes version - 1.19
* Using EKS (yes/no), if so version? yes
* Kubeflow version - 1.4 - Vanilla deployment
* AWS build number
* AWS service targeted (S3, RDS, etc.)

**Screenshots**

**Additional context**

**Comment by wenjinsitu** [comment]
@kanwaljitkhurmi 
Could you also paste your training job yaml file?

**Comment by wenjinsitu** [comment]
got it fixed:
"deleted all pending CRDs and deleted the operator and it came back up fine."

**Comment by kanwaljitkhurmi** [comment]
deleted all pending CRDs and deleted the operator and it came back up fine.

**Comment by kanwaljitkhurmi** [comment]
deleted all pending CRDs and deleted the operator and it came back up fine.
