### ISSUE TITLE
Notebook server creation fails if PV is not used for workspace

### ISSUE THREAD

**Issue by surajkota** [awslabs/kubeflow-manifests#33]
### Description of issue
Succeeds with scipy image and KF default pytorch images but fails on DLC based images

Logs
```
Using deprecated annotation `kubectl.kubernetes.io/default-logs-container` in pod/skota-2-0. Please use `kubectl.kubernetes.io/default-container` instead
/opt/conda/lib/python3.8/site-packages/jupyter_server_mathjax/app.py:40: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  help=_("""The MathJax.js configuration file that is to be used."""),
[I 2021-11-30 20:38:10.802 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[W 2021-11-30 20:38:10.806 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-11-30 20:38:10.806 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-11-30 20:38:10.806 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-11-30 20:38:10.806 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-11-30 20:38:10.813 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-11-30 20:38:10.813 ServerApp] jupyterlab_git | extension was successfully linked.
[W 2021-11-30 20:38:10.822 ServerApp] [Errno 13] Permission denied: '/home/jovyan/.local'
[I 2021-11-30 20:38:10.822 ServerApp] nbdime | extension was successfully linked.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 567, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 537, in initialize_server
    serverapp.initialize(
  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2320, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1739, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 95, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 11, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```

### Steps to reproduce:
Create a notebook with AWS images for notebook and check the option  `Don't use Persistent Storage for User's home` under workspace volume

**Comment by mbaijal** [comment]
This issue has been fixed on the latest notebook containers.
