### ISSUE TITLE
Automated script for load balancer hits LB name length error

### ISSUE THREAD

**Issue by BrianF-tessera** [awslabs/kubeflow-manifests#552]
**Describe the bug**
When adding a load balancer to a deployed kubeflow cluster deployed from 1.6.1 on EKS 1.23 with RDS and S3 add-ons the internet-facing load balancer works fine, but when deploying an internal load balancer scheme, the following errors are thrown with partial prior stack trace to show where in the process it occurs

```
configmap/istio-ingress-parameters unchanged

configmap/aws-load-balancer-controller-config unchanged

service/aws-load-balancer-webhook-service unchanged

deployment.apps/aws-load-balancer-controller unchanged

certificate.cert-manager.io/aws-load-balancer-serving-cert unchanged

issuer.cert-manager.io/aws-load-balancer-selfsigned-issuer unchanged

ingressclassparams.elbv2.k8s.aws/alb created

Warning: Detected changes to resource istio-ingress which is currently being deleted.

ingress.networking.k8s.io/istio-ingress unchanged

ingressclass.networking.k8s.io/alb unchanged

validatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook configured

INFO:__main__:waiting for ALB creation ...

INFO:__main__: internal-k8s-istiosys-istioing-7c973603e9-1312983502.us-east-1.elb.amazonaws.com waiting for ALB status = active ...

ERROR:e2e.utils.aws.elbv2:Failed to describe load balancer internal-k8s-istiosys-istioing-7c973603e9
Traceback (most recent call last):

  File "/mnt/c/users/bfrench/Documents/Code/kubeflow-manifests/tests/e2e/utils/aws/elbv2.py", line 28, in describe
    response = self.elbv2_client.describe_load_balancers(
  File "/home/bfrench/.local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/bfrench/.local/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeLoadBalancers operation: The load balancer name 'internal-k8s-istiosys-istioing-7c973603e9' cannot be longer than '32' characters
ERROR:e2e.utils.aws.elbv2:Failed to describe load balancer internal-k8s-istiosys-istioing-7c973603e9
Traceback (most recent call last):
  File "/mnt/c/users/bfrench/Documents/Code/kubeflow-manifests/tests/e2e/utils/aws/elbv2.py", line 28, in describe
    response = self.elbv2_client.describe_load_balancers(
  File "/home/bfrench/.local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/bfrench/.local/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeLoadBalancers operation: The load balancer name 'internal-k8s-istiosys-istioing-7c973603e9' cannot be longer than '32' characters

```

**Steps To Reproduce**

Deploy cluster onto EKS 1.23 using the 1.6.1 deployment with kustomize. Deploy an internet-facing load balancer that works correctly, tear it down with the automated script, then attempt to launch with internal load balancer.

**Expected behavior**
Internal-facing load balancer provisions successfully

**Environment**
* Kubernetes version
* Using EKS (yes/no), yes 1.23
* Kubeflow version 1.6.1
* AWS build number release-v1.6.1-aws-b1.0.0
* AWS service targeted (S3, RDS, etc.) Load Balancer

**Additional context**
none

**Comment by surajkota** [comment]
Hi @BrianF-tessera, while we try to replicate it and figure out the issue, I want to unblock you first from using a load balancer with internet schema set to `internal`

Can you try the following steps?

- Create a internet-facing load balancer as you did previously
- Run the following command to update the scheme to internal
   - `kubectl annotate ingress --overwrite -n istio-system istio-ingress alb.ingress.kubernetes.io/scheme='internal'`
- Wait for the new load balancer to be provisioned which has scheme as internal and attached to private subnets.

E.g.
```
kubectl get ingress istio-ingress -n istio-system -oyaml | grep hostname
      - hostname: internal-k8s-istiosys-istioing-xxxxxx-xxxxxx.us-west-2.elb.amazonaws.com
```
