### ISSUE TITLE
evalsymlink failure on '../../upstream/common/cert-manager/cert-manager/base'

### ISSUE THREAD

**Issue by marshalld68** [awslabs/kubeflow-manifests#559]
**Describe the bug**
Following directions here https://awslabs.github.io/kubeflow-manifests/docs/ for the manual deployment with kustomize: https://awslabs.github.io/kubeflow-manifests/docs/deployment/rds-s3/guide/

**Steps To Reproduce**
make deploy-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=rds-s3

**Expected behavior**
Installation completes successfully

**Environment**
* 1.24
* EKS: yes
* n/a
* n/a
* 

**Screenshots**
n/a

**Additional context**

```
 make deploy-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=rds-s3
test kubeflow || (echo Please export CLUSTER_NAME variable ; exit 1)
test us-east-1 || (echo Please export CLUSTER_REGION variable ; exit 1)
aws eks update-kubeconfig --name kubeflow --region us-east-1
Updated context <arn here> in .kube/config
yq e '.cluster.name=env(CLUSTER_NAME)' -i tests/e2e/utils/ack_sm_controller_bootstrap/config.yaml
yq e '.cluster.region=env(CLUSTER_REGION)' -i tests/e2e/utils/ack_sm_controller_bootstrap/config.yaml
cd tests/e2e && PYTHONPATH=.. python3.8 utils/ack_sm_controller_bootstrap/setup_sm_controller_req.py
=================================================================
                          Reading Config
=================================================================
=================================================================
        Create OIDC IAM role for ACK SageMaker Controller
=================================================================
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name kf-ack-sm-controller-role-kubeflow already exists.
Try running cleanup_sm_controller_req.py
=================================================================
         Writing params.env for ACK SageMaker Controller
=================================================================
Params file written to : ../../awsconfigs/common/ack-sagemaker-controller/params.env
Editing ./utils/ack_sm_controller_bootstrap/config.yaml with appropriate values...
Config file written to : ./utils/ack_sm_controller_bootstrap/config.yaml
=================================================================
                             SUCCESS
=================================================================
cd tests/e2e && PYTHONPATH=.. python3.8 utils/kubeflow_installation.py --deployment_option rds-s3 --installation_option kustomize --cluster_name kubeflow
kubeflow
=================================================================
       Installing kubeflow rds-s3 deployment with kustomize
=================================================================
==========Installing cert-manager==========
Error: absolute path error in '../../upstream/common/cert-manager/cert-manager/base' : evalsymlink failure on '../../upstream/common/cert-manager/cert-manager/base' : lstat /root/cloud-dsp/cluster/aws/installer/kubeflow-manifests/upstream: no such file or directory
Traceback (most recent call last):
  File "utils/kubeflow_installation.py", line 278, in <module>
    install_kubeflow(
  File "utils/kubeflow_installation.py", line 79, in install_kubeflow
    install_component(
  File "utils/kubeflow_installation.py", line 133, in install_component
    apply_kustomize(kustomize_path)
  File "/root/cloud-dsp/cluster/aws/installer/kubeflow-manifests/tests/e2e/utils/utils.py", line 198, in apply_kustomize
    assert build_retcode == 0
AssertionError
make: *** [deploy-kubeflow] Error 1

```

**Comment by ananth102** [comment]
Hi marshalld68, seems like the upstream folder might not be present, you can clone it with:
`git clone --branch v1.6.1 https://github.com/kubeflow/manifests.git upstream`

**Comment by ananth102** [comment]
Closing as issue seems to be resolved.
