### ISSUE TITLE
Kubeflow installation on EKS fails - timed out while istio installation

### ISSUE THREAD

**Issue by AbhiDub** [awslabs/kubeflow-manifests#620]
**Describe the bug**
While installing using Helm charts from docker ubuntu machine, installation over AWS EKS fails with below error. It fails while setting up istio-system namespace

running command: kubectl wait --for=condition=ready pod -l 'app in (istio-ingressgateway, istiod)' --timeout=240s -n istio-system
timed out waiting for the condition on pods/istio-ingressgateway-67d6475549-7mjvj
timed out waiting for the condition on pods/istiod-c8965d9c5-m9nvm
Waiting for istio-1-14 pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (istio-ingressgateway, istiod)' --timeout=240s -n istio-system
timed out waiting for the condition on pods/istio-ingressgateway-67d6475549-7mjvj
timed out waiting for the condition on pods/istiod-c8965d9c5-m9nvm
Traceback (most recent call last):
  File "utils/kubeflow_installation.py", line 278, in <module>
    install_kubeflow(
  File "utils/kubeflow_installation.py", line 79, in install_kubeflow
    install_component(
  File "utils/kubeflow_installation.py", line 143, in install_component
    validate_component_installation(installation_config, component_name)
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.8/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "utils/kubeflow_installation.py", line 155, in validate_component_installation
    kubectl_wait_pods(value, namespace, key)
  File "/kubeflow-manifests/tests/e2e/utils/utils.py", line 266, in kubectl_wait_pods
    assert os.system(cmd) == 0
AssertionError
Makefile:102: recipe for target 'deploy-kubeflow' failed

**Steps To Reproduce**
Vanilla installation using manifests. Execute this command after prerequisites are completed
make delete-kubeflow INSTALLATION_OPTION=helm DEPLOYMENT_OPTION=vanilla

**Expected behavior**

**Environment**
* Kubernetes version
* Using EKS (yes/no), if so version? Yes, 1.24
* Kubeflow version - v1.6.1-aws-b1.0.1
* AWS build number 
* AWS service targeted (S3, RDS, etc.)
None
**Screenshots**

**Additional context**
while checking pod it shows CrashLoopBackOff
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1

**Comment by ryansteakley** [comment]
What do the pod logs for istio say? Can you share the output of kubectl get pods -A

**Comment by AbhiDub** [comment]
to add - we're using Graviton r6g processor (linux arm64 V8)

**Comment by surajkota** [comment]
based on https://github.com/istio/istio/issues/22463, this looks like an intermittent issue and deleting the istiod pod might fix the issue.

**Comment by surajkota** [comment]
Closing due to inactivity. Feel free to reopen if the issue is not resolved

**Comment by surajkota** [comment]
@keenborder786 Please open a new issue and use the bug template to provide environment details amd steps to reproduce

**Comment by HanHoRang31** [comment]
I have the same problem. The oidc-authservice pod is not running. When I open the log, the following is displayed
| exec ./oidc-authservice: exec format error 
It is said that this is because the architecture is different, but what should I do?
