### ISSUE TITLE
Kubeflow setup following tutorial not deploying, hanging up on cert-manager

### ISSUE THREAD

**Issue by palmerss** [awslabs/kubeflow-manifests#804]
**Describe the bug**
Hello, I have been following the tutorial [here](https://awslabs.github.io/kubeflow-manifests/docs/deployment/) from the prerequisites to creating the EKS Cluster to Vanilla installation via Manifest Deployment. I am currently using cloud9 to set up everything on a t2.medium instance.

When getting to the point where I run
`make deploy-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=vanilla`
The system hangs up when installing cert-manager due to timeouts, output from install is posted below

```
palmerss:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $ make deploy-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=vanilla
test A101xCluster || (echo Please export CLUSTER_NAME variable ; exit 1)
test us-east-2 || (echo Please export CLUSTER_REGION variable ; exit 1)
aws eks update-kubeconfig --name A101xCluster --region us-east-2
Added new context arn:aws:eks:us-east-2:837587209284:cluster/A101xCluster to /home/ubuntu/.kube/config
yq e '.cluster.name=env(CLUSTER_NAME)' -i tests/e2e/utils/ack_sm_controller_bootstrap/config.yaml
yq e '.cluster.region=env(CLUSTER_REGION)' -i tests/e2e/utils/ack_sm_controller_bootstrap/config.yaml
cd tests/e2e && PYTHONPATH=.. python3.8 utils/ack_sm_controller_bootstrap/setup_sm_controller_req.py
/home/ubuntu/environment/kubeflow-manifests/tests/e2e/utils/utils.py:271: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if retcode is not 0:
=================================================================
                          Reading Config                         
=================================================================
=================================================================
        Create OIDC IAM role for ACK SageMaker Controller        
=================================================================
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name kf-ack-sm-controller-role-A101xCluster already exists.
Try running cleanup_sm_controller_req.py
=================================================================
         Writing params.env for ACK SageMaker Controller         
=================================================================
Params file written to : ../../awsconfigs/common/ack-sagemaker-controller/params.env
Editing ./utils/ack_sm_controller_bootstrap/config.yaml with appropriate values...
Config file written to : ./utils/ack_sm_controller_bootstrap/config.yaml
=================================================================
                             SUCCESS                             
=================================================================
cd tests/e2e && PYTHONPATH=.. python3.8 utils/kubeflow_installation.py --deployment_option vanilla --installation_option kustomize --pipeline_s3_credential_option irsa --cluster_name A101xCluster
A101xCluster
=================================================================
 Installing kubeflow vanilla deployment with kustomize with irsa 
=================================================================
==========Installing cert-manager==========
namespace/cert-manager created
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io created
serviceaccount/cert-manager created
serviceaccount/cert-manager-cainjector created
serviceaccount/cert-manager-webhook created
role.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
role.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
role.rbac.authorization.k8s.io/cert-manager:leaderelection created
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrole.rbac.authorization.k8s.io/cert-manager-edit created
clusterrole.rbac.authorization.k8s.io/cert-manager-view created
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
rolebinding.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager:leaderelection created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
configmap/cert-manager-webhook created
service/cert-manager created
service/cert-manager-webhook created
deployment.apps/cert-manager created
deployment.apps/cert-manager-cainjector created
deployment.apps/cert-manager-webhook created
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
wait for 60s for cert-manager-webhook resource to be ready...
Waiting for cert-manager pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/instance in (cert-manager)' --timeout=240s -n cert-manager
timed out waiting for the condition on pods/cert-manager-74d949c895-bsdlq
timed out waiting for the condition on pods/cert-manager-cainjector-d9bc5979d-jbtg6
timed out waiting for the condition on pods/cert-manager-webhook-84b7ddd796-h74wh
error: unknown flag: --timeout
See 'kubectl describe --help' for usage.
Waiting for cert-manager pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/instance in (cert-manager)' --timeout=240s -n cert-manager
timed out waiting for the condition on pods/cert-manager-74d949c895-bsdlq
timed out waiting for the condition on pods/cert-manager-cainjector-d9bc5979d-jbtg6
timed out waiting for the condition on pods/cert-manager-webhook-84b7ddd796-h74wh
error: unknown flag: --timeout
See 'kubectl describe --help' for usage.
Waiting for cert-manager pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/instance in (cert-manager)' --timeout=240s -n cert-manager
timed out waiting for the condition on pods/cert-manager-74d949c895-bsdlq
timed out waiting for the condition on pods/cert-manager-cainjector-d9bc5979d-jbtg6
timed out waiting for the condition on pods/cert-manager-webhook-84b7ddd796-h74wh
error: unknown flag: --timeout
See 'kubectl describe --help' for usage.
Traceback (most recent call last):
  File "utils/kubeflow_installation.py", line 324, in <module>
    install_kubeflow(
  File "utils/kubeflow_installation.py", line 101, in install_kubeflow
    install_component(
  File "utils/kubeflow_installation.py", line 180, in install_component
    validate_component_installation(installation_config, component_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "utils/kubeflow_installation.py", line 192, in validate_component_installation
    kubectl_wait_pods(value, namespace, key)
  File "/home/ubuntu/environment/kubeflow-manifests/tests/e2e/utils/utils.py", line 275, in kubectl_wait_pods
    raise Exception("Timeout/error waiting for pod condition")
Exception: Timeout/error waiting for pod condition
make: *** [Makefile:104: deploy-kubeflow] Error 1
palmerss:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $
```

**Steps To Reproduce**
Follow the guides at https://awslabs.github.io/kubeflow-manifests/docs/deployment/
go through pre-requisites
go through Create an EKS cluster
go through Vanilla installation

**Expected behavior**
That the installation is successful and that I can move on to access the kubeflow GUI 

**Environment**
* Kubernetes version 1.25 (I think this is the version you specify when creating EKS cluster right?)
* Using EKS (yes/no), if so version? yes, 1.25
* Kubeflow version 1.7
* AWS build number: not sure, is this the version of aws cli that I'm using?

I'm also looking to integrate my cluster with EFS, but I don't believe that is related to this issue, but something to maybe consider if there's anything on this setup that may block that ability.

**Comment by ananth102** [comment]
Are there any errors in the pod logs or in the pod description. Retrying the installation might help. To uninstall use `make delete-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=vanilla`.

**Comment by palmerss** [comment]
> Are there any errors in the pod logs or in the pod description. Retrying the installation might help. To uninstall use `make delete-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=vanilla`.

Restarted from a fresh environment and all, here's what I get for pod logs/descriptions, also was sure to follow the tutorial in a very detailed manner.

```
ubuntu:~/environment $ kubectl get pods -n cert-manager
NAME                                      READY   STATUS    RESTARTS   AGE
cert-manager-74d949c895-cbp9n             0/1     Pending   0          2m53s
cert-manager-cainjector-d9bc5979d-mbdh7   0/1     Pending   0          2m53s
cert-manager-webhook-84b7ddd796-vvm2w     0/1     Pending   0          2m53s
ubuntu:~/environment $ kubectl logs cert-manager-74d949c895-cbp9n 
Error from server (NotFound): pods "cert-manager-74d949c895-cbp9n" not found
ubuntu:~/environment $ kubectl logs cert-manager-cainjector-d9bc5979d-mbdh7 
Error from server (NotFound): pods "cert-manager-cainjector-d9bc5979d-mbdh7" not found
ubuntu:~/environment $ kubectl logs cert-manager-webhook-84b7ddd796-vvm2w 
Error from server (NotFound): pods "cert-manager-webhook-84b7ddd796-vvm2w" not found
ubuntu:~/environment $ kubectl describe cert-manager-74d949c895-cbp9n 
error: the server doesn't have a resource type "cert-manager-74d949c895-cbp9n"
ubuntu:~/environment $ kubectl describe cert-manager-cainjector-d9bc5979d-mbdh7
error: the server doesn't have a resource type "cert-manager-cainjector-d9bc5979d-mbdh7"
ubuntu:~/environment $ kubectl describe cert-manager-webhook-84b7ddd796-vvm2w
error: the server doesn't have a resource type "cert-manager-webhook-84b7ddd796-vvm2w"
```

**Comment by ananth102** [comment]
@palmerss Try using `kubectl describe pod <pod> -n cert-manager` to describe the pod

**Comment by palmerss** [comment]
Thanks! Sorry, I'm new to kubernetes/kubeflow (:

```
ubuntu:~/environment $ kubectl get pods -n cert-manager
NAME                                      READY   STATUS    RESTARTS   AGE
cert-manager-74d949c895-cbp9n             0/1     Pending   0          8m46s
cert-manager-cainjector-d9bc5979d-mbdh7   0/1     Pending   0          8m46s
cert-manager-webhook-84b7ddd796-vvm2w     0/1     Pending   0          8m46s
ubuntu:~/environment $ kubectl describe pod cert-manager-74d949c895-cbp9n -n cert-manager                                                                                                                                                                          
Name:             cert-manager-74d949c895-cbp9n
Namespace:        cert-manager
Priority:         0
Service Account:  cert-manager
Node:             <none>
Labels:           app=cert-manager
                  app.kubernetes.io/component=controller
                  app.kubernetes.io/instance=cert-manager
                  app.kubernetes.io/name=cert-manager
                  app.kubernetes.io/version=v1.10.1
                  pod-template-hash=74d949c895
Annotations:      prometheus.io/path: /metrics
                  prometheus.io/port: 9402
                  prometheus.io/scrape: true
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/cert-manager-74d949c895
Containers:
  cert-manager-controller:
    Image:      quay.io/jetstack/cert-manager-controller:v1.10.1
    Port:       9402/TCP
    Host Port:  0/TCP
    Args:
      --v=2
      --cluster-resource-namespace=$(POD_NAMESPACE)
      --leader-election-namespace=kube-system
    Environment:
      POD_NAMESPACE:  cert-manager (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kjp6s (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-kjp6s:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  88s (x17 over 81m)  default-scheduler  no nodes available to schedule pods
ubuntu:~/environment $ kubectl describe pod cert-manager-cainjector-d9bc5979d-mbdh7 -n cert-manager                                                                                                                                                                
Name:             cert-manager-cainjector-d9bc5979d-mbdh7
Namespace:        cert-manager
Priority:         0
Service Account:  cert-manager-cainjector
Node:             <none>
Labels:           app=cainjector
                  app.kubernetes.io/component=cainjector
                  app.kubernetes.io/instance=cert-manager
                  app.kubernetes.io/name=cainjector
                  app.kubernetes.io/version=v1.10.1
                  pod-template-hash=d9bc5979d
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/cert-manager-cainjector-d9bc5979d
Containers:
  cert-manager-cainjector:
    Image:      quay.io/jetstack/cert-manager-cainjector:v1.10.1
    Port:       <none>
    Host Port:  <none>
    Args:
      --v=2
      --leader-election-namespace=kube-system
    Environment:
      POD_NAMESPACE:  cert-manager (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7jjs9 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-7jjs9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  2m13s (x17 over 82m)  default-scheduler  no nodes available to schedule pods
ubuntu:~/environment $ kubectl describe pod cert-manager-webhook-84b7ddd796-vvm2w -n cert-manager                                                                                                                                                                  
Name:             cert-manager-webhook-84b7ddd796-vvm2w
Namespace:        cert-manager
Priority:         0
Service Account:  cert-manager-webhook
Node:             <none>
Labels:           app=webhook
                  app.kubernetes.io/component=webhook
                  app.kubernetes.io/instance=cert-manager
                  app.kubernetes.io/name=webhook
                  app.kubernetes.io/version=v1.10.1
                  pod-template-hash=84b7ddd796
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/cert-manager-webhook-84b7ddd796
Containers:
  cert-manager-webhook:
    Image:       quay.io/jetstack/cert-manager-webhook:v1.10.1
    Ports:       10250/TCP, 6080/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      --v=2
      --secure-port=10250
      --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
      --dynamic-serving-ca-secret-name=cert-manager-webhook-ca
      --dynamic-serving-dns-names=cert-manager-webhook
      --dynamic-serving-dns-names=cert-manager-webhook.$(POD_NAMESPACE)
      --dynamic-serving-dns-names=cert-manager-webhook.$(POD_NAMESPACE).svc
    Liveness:   http-get http://:6080/livez delay=60s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:6080/healthz delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  cert-manager (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8lfbq (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-8lfbq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  2m36s (x17 over 82m)  default-scheduler  no nodes available to schedule pods

```
So here is my output for each of the pods, looking at the warning messages, is this failing because I have no nodes running currently? I have configured my cluster to have 0 persistent nodes as I figured it would launch a node when needed...Here's the command I used to create the cluster

```
eksctl create cluster \
	--name ${CLUSTER_NAME} \
	--version 1.25 \
	--region ${CLUSTER_REGION} \
	--nodegroup-name kubeflow-nodes \
	--node-type g5.xlarge \
	--nodes-min 0 \
	--nodes-max 10 \
	--managed \
	--with-oidc
```

**Comment by ananth102** [comment]
No worries! Yea it seems like your cluster does not have enough nodes for scheduling. You will typically need at least 5 m5.xlarge nodes.

**Comment by palmerss** [comment]
> No worries! Yea it seems like your cluster does not have enough nodes for scheduling. You will typically need at least 5 m5.xlarge nodes.

Is it ok if I were to scale these down after the installation? Or do they need to always be running? At least my hope is that as jobs are submitted to the cluster that nodes are spun up and spun down as jobs start/finish

**Comment by ananth102** [comment]
The pods might be evicted from the nodes if there is no compute available. In which case you might experience failures.

**Comment by palmerss** [comment]
Alright, I'm getting further now, I created my cluster like so
```
eksctl create cluster \
--name ${CLUSTER_NAME} \
--version 1.25 \
--region ${CLUSTER_REGION} \
--nodegroup-name linux-nodes \
--node-type m5.xlarge \
--nodes 5 \
--nodes-min 5 \
--nodes-max 10 \
--managed \
--with-oidc
```

and here are my logs from install/checking on pods that are hung up

```
ubuntu:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $ make deploy-kubeflow INSTALLATION_OPTION=kustomize DEPLOYMENT_OPTION=vanilla
test A10Cluster || (echo Please export CLUSTER_NAME variable ; exit 1)
test us-east-2 || (echo Please export CLUSTER_REGION variable ; exit 1)
aws eks update-kubeconfig --name A10Cluster --region us-east-2
Updated context arn:aws:eks:us-east-2:837587209284:cluster/A10Cluster in /home/ubuntu/.kube/config
yq e '.cluster.name=env(CLUSTER_NAME)' -i tests/e2e/utils/ack_sm_controller_bootstrap/config.yaml
yq e '.cluster.region=env(CLUSTER_REGION)' -i tests/e2e/utils/ack_sm_controller_bootstrap/config.yaml
cd tests/e2e && PYTHONPATH=.. python3.8 utils/ack_sm_controller_bootstrap/setup_sm_controller_req.py
=================================================================
                          Reading Config
=================================================================
=================================================================
        Create OIDC IAM role for ACK SageMaker Controller
=================================================================
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name kf-ack-sm-controller-role-A10Cluster already exists.
Try running cleanup_sm_controller_req.py
=================================================================
         Writing params.env for ACK SageMaker Controller
=================================================================
Params file written to : ../../awsconfigs/common/ack-sagemaker-controller/params.env
Editing ./utils/ack_sm_controller_bootstrap/config.yaml with appropriate values...
Config file written to : ./utils/ack_sm_controller_bootstrap/config.yaml
=================================================================
                             SUCCESS
=================================================================
cd tests/e2e && PYTHONPATH=.. python3.8 utils/kubeflow_installation.py --deployment_option vanilla --installation_option kustomize --pipeline_s3_credential_option irsa --cluster_name A10Cluster
A10Cluster
=================================================================
 Installing kubeflow vanilla deployment with kustomize with irsa
=================================================================
==========Installing cert-manager==========
namespace/cert-manager created
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io created
serviceaccount/cert-manager created
serviceaccount/cert-manager-cainjector created
serviceaccount/cert-manager-webhook created
role.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
role.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
role.rbac.authorization.k8s.io/cert-manager:leaderelection created
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrole.rbac.authorization.k8s.io/cert-manager-edit created
clusterrole.rbac.authorization.k8s.io/cert-manager-view created
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
rolebinding.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager:leaderelection created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
configmap/cert-manager-webhook created
service/cert-manager created
service/cert-manager-webhook created
deployment.apps/cert-manager created
deployment.apps/cert-manager-cainjector created
deployment.apps/cert-manager-webhook created
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
wait for 60s for cert-manager-webhook resource to be ready...
Waiting for cert-manager pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app.kubernetes.io/instance in (cert-manager)' --timeout=240s -n cert-manager
pod/cert-manager-74d949c895-mm28b condition met
pod/cert-manager-cainjector-d9bc5979d-rf5nn condition met
pod/cert-manager-webhook-84b7ddd796-rdrml condition met
All cert-manager pods are running!
==========Installing istio==========
customresourcedefinition.apiextensions.k8s.io/authorizationpolicies.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/istiooperators.install.istio.io created
customresourcedefinition.apiextensions.k8s.io/peerauthentications.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/proxyconfigs.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/requestauthentications.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceentries.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/sidecars.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/telemetries.telemetry.istio.io created
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/wasmplugins.extensions.istio.io created
customresourcedefinition.apiextensions.k8s.io/workloadentries.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/workloadgroups.networking.istio.io created
namespace/istio-system created
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
serviceaccount/istio-ingressgateway-service-account created
serviceaccount/istio-reader-service-account created
serviceaccount/istiod created
serviceaccount/istiod-service-account created
role.rbac.authorization.k8s.io/istio-ingressgateway-sds created
role.rbac.authorization.k8s.io/istiod created
role.rbac.authorization.k8s.io/istiod-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-reader-clusterrole-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-reader-istio-system created
clusterrole.rbac.authorization.k8s.io/istiod-clusterrole-istio-system created
clusterrole.rbac.authorization.k8s.io/istiod-gateway-controller-istio-system created
clusterrole.rbac.authorization.k8s.io/istiod-istio-system created
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds created
rolebinding.rbac.authorization.k8s.io/istiod created
rolebinding.rbac.authorization.k8s.io/istiod-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-reader-clusterrole-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-reader-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istiod-clusterrole-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istiod-gateway-controller-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istiod-istio-system created
configmap/istio created
configmap/istio-sidecar-injector created
service/istio-ingressgateway created
service/istiod created
deployment.apps/istio-ingressgateway created
deployment.apps/istiod created
poddisruptionbudget.policy/istio-ingressgateway created
poddisruptionbudget.policy/istiod created
envoyfilter.networking.istio.io/stats-filter-1.13 created
envoyfilter.networking.istio.io/stats-filter-1.14 created
envoyfilter.networking.istio.io/stats-filter-1.15 created
envoyfilter.networking.istio.io/stats-filter-1.16 created
envoyfilter.networking.istio.io/tcp-stats-filter-1.13 created
envoyfilter.networking.istio.io/tcp-stats-filter-1.14 created
envoyfilter.networking.istio.io/tcp-stats-filter-1.15 created
envoyfilter.networking.istio.io/tcp-stats-filter-1.16 created
envoyfilter.networking.istio.io/x-forwarded-host created
gateway.networking.istio.io/istio-ingressgateway created
authorizationpolicy.security.istio.io/global-deny-all created
authorizationpolicy.security.istio.io/istio-ingressgateway created
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector created
validatingwebhookconfiguration.admissionregistration.k8s.io/istio-validator-istio-system created
Waiting for istio pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (istio-ingressgateway, istiod)' --timeout=240s -n istio-system
pod/istio-ingressgateway-67f7b5f88d-jb4zf condition met
pod/istiod-56f7cf9bd6-jkkvg condition met
All istio pods are running!
==========Installing dex==========
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
namespace/auth created
customresourcedefinition.apiextensions.k8s.io/authcodes.dex.coreos.com created
serviceaccount/dex created
clusterrole.rbac.authorization.k8s.io/dex created
clusterrolebinding.rbac.authorization.k8s.io/dex created
configmap/dex created
secret/dex-oidc-client created
service/dex created
deployment.apps/dex created
virtualservice.networking.istio.io/dex created
Waiting for dex pods to be ready ...
running command: kubectl wait --for=condition=ready pod -l 'app in (dex)' --timeout=240s -n auth
pod/dex-56d9748f89-xh4nr condition met
All dex pods are running!
==========Installing oidc-authservice==========
ubuntu:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $ kubectl get pods -n cert-manager
NAME                                      READY   STATUS    RESTARTS   AGE
cert-manager-74d949c895-mm28b             1/1     Running   0          15m
cert-manager-cainjector-d9bc5979d-rf5nn   1/1     Running   0          15m
cert-manager-webhook-84b7ddd796-rdrml     1/1     Running   0          15m
ubuntu:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $ kubectl get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
authservice-0                           0/1     Pending   0          14m
istio-ingressgateway-67f7b5f88d-jb4zf   1/1     Running   0          14m
istiod-56f7cf9bd6-jkkvg                 1/1     Running   0          14m
ubuntu:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $ kubectl get pods -n auth
NAME                   READY   STATUS    RESTARTS   AGE
dex-56d9748f89-xh4nr   1/1     Running   0          14m
ubuntu:~/environment/kubeflow-manifests ((v1.7.0-aws-b1.0.3)) $ kubectl describe pod authservice-0 -n istio-system
Name:             authservice-0
Namespace:        istio-system
Priority:         0
Service Account:  authservice
Node:             <none>
Labels:           app=authservice
                  controller-revision-hash=authservice-7bd6b4b965
                  statefulset.kubernetes.io/pod-name=authservice-0
Annotations:      sidecar.istio.io/inject: false
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    StatefulSet/authservice
Containers:
  authservice:
    Image:      gcr.io/arrikto/kubeflow/oidc-authservice:e236439
    Port:       8080/TCP
    Host Port:  0/TCP
    Readiness:  http-get http://:8081/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      oidc-authservice-client      Secret     Optional: false
      oidc-authservice-parameters  ConfigMap  Optional: false
    Environment:                   <none>
    Mounts:
      /var/lib/authservice from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-m5wpg (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  authservice-pvc
    ReadOnly:   false
  kube-api-access-m5wpg:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  5m13s  default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition

```
